---
version: '3'

services:
  gitlab:
    image: docker.io/gitlab/gitlab-ce:latest
    restart: always
    hostname: gitlab.jlmillerelectric.io
    ports:
      - "192.168.1.21:80:80"
      - "192.168.1.21:443:443"    
      - "192.168.1.21:2222:22"    
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.jlmillerelectric.io'
        letsencrypt['enable'] = false
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = '/etc/gitlab/ssl/gitlab.jlmillerelectric.io.crt'
        nginx['ssl_certificate_key'] = '/etc/gitlab/ssl/gitlab.jlmillerelectric.io.key'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = '192.168.1.20'
        gitlab_rails['smtp_port'] = 25
        gitlab_rails['smtp_domain'] = 'jlmillerelectric.io'
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_openssl_verify_mode'] = 'none'
        gitlab_rails['smtp_enable_starttls_auto'] = false
        gitlab_rails['smtp_ssl'] = false
        gitlab_rails['smtp_force_ssl'] = false
        gitlab_rails['gitlab_email_from'] = 'gitlab@jlmillerelectric.io'
        gitlab_rails['gitlab_email_reply_to'] = 'noreply@jlmillerelectric.io'
    volumes:
      - /service/gitlab/config:/etc/gitlab
      - /service/gitlab/logs:/var/log/gitlab
      - /service/gitlab/data:/var/opt/gitlab
      - ./ssl:/etc/gitlab/ssl
    networks:
      - gitlab-network

networks:
  gitlab-network:
    driver: bridge

